"""
Base Agent - Abstract agent class for all monitoring/detection agents.
All agents run as Ray actors consuming Kafka telemetry and producing alerts.
"""
from __future__ import annotations
import json
import logging
import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field, asdict
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class Alert:
    """Standard alert generated by detection agents."""
    alert_id: str = ""
    agent_name: str = ""
    timestamp: float = 0.0
    severity: str = "medium"  # "low", "medium", "high", "critical"
    confidence: float = 0.0
    alert_type: str = ""
    mitre_tactic: str = ""
    mitre_technique: str = ""
    source_ip: str | None = None
    source_host: str | None = None
    target_ip: str | None = None
    target_host: str | None = None
    user_id: str | None = None
    description: str = ""
    evidence: list[dict[str, Any]] = field(default_factory=list)
    recommended_actions: list[str] = field(default_factory=list)
    raw_events: list[str] = field(default_factory=list)  # event UIDs

    def __post_init__(self):
        if not self.alert_id:
            self.alert_id = f"alert-{uuid.uuid4().hex[:12]}"
        if not self.timestamp:
            self.timestamp = time.time()

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class StrategyProposal:
    """Containment strategy proposed by an agent."""
    strategy_id: str = ""
    incident_id: str = ""
    agent_name: str = ""
    actions: list[str] = field(default_factory=list)
    confidence: float = 0.0
    residual_risk: float = 0.0
    impact_estimate: dict[str, Any] = field(default_factory=dict)
    constraints: list[str] = field(default_factory=list)
    timestamp: float = 0.0

    def __post_init__(self):
        if not self.strategy_id:
            self.strategy_id = f"str-{uuid.uuid4().hex[:12]}"
        if not self.timestamp:
            self.timestamp = time.time()

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class BaseAgent(ABC):
    """Abstract base class for all AMCDS monitoring agents."""

    def __init__(self, agent_name: str, kafka_bootstrap: str = "kafka:9092",
                 redis_host: str = "redis", redis_port: int = 6379):
        self.agent_name = agent_name
        self.kafka_bootstrap = kafka_bootstrap
        self.redis_host = redis_host
        self.redis_port = redis_port
        self._producer = None
        self._consumer = None
        self._redis = None
        self._running = False
        self._alert_count = 0
        self._event_count = 0

    def initialize(self) -> None:
        """Initialize Kafka and Redis connections."""
        from messaging.producers.base_producer import BaseProducer
        from messaging.consumers.base_consumer import BaseConsumer
        self._producer = BaseProducer(self.kafka_bootstrap)
        self._producer.connect()
        self._consumer = BaseConsumer(
            bootstrap_servers=self.kafka_bootstrap,
            group_id=f"agent-{self.agent_name}",
            topics=self.get_subscribed_topics(),
        )
        self._consumer.connect()
        try:
            import redis
            self._redis = redis.Redis(host=self.redis_host, port=self.redis_port, decode_responses=True)
            self._redis.ping()
        except Exception:
            logger.warning("Redis not available for %s", self.agent_name)
            self._redis = None

    @abstractmethod
    def get_subscribed_topics(self) -> list[str]:
        """Return list of Kafka topics this agent consumes."""
        ...

    @abstractmethod
    def analyze(self, event: dict[str, Any]) -> list[Alert]:
        """Analyze a single event and return any alerts."""
        ...

    @abstractmethod
    def propose_strategy(self, alert: Alert) -> StrategyProposal | None:
        """Propose a containment strategy for a given alert."""
        ...

    def process_event(self, event: dict[str, Any]) -> None:
        """Process a single event: analyze and publish alerts."""
        self._event_count += 1
        alerts = self.analyze(event)
        for alert in alerts:
            self._publish_alert(alert)
            strategy = self.propose_strategy(alert)
            if strategy:
                self._publish_strategy(strategy)

    def _publish_alert(self, alert: Alert) -> None:
        """Publish an alert to the alerts.raw topic."""
        self._alert_count += 1
        if self._producer:
            self._producer.produce("alerts.raw", alert.to_dict(), key=alert.alert_id)
        logger.info("[%s] Alert: %s (confidence=%.2f)", self.agent_name, alert.alert_type, alert.confidence)

    def _publish_strategy(self, strategy: StrategyProposal) -> None:
        if self._producer:
            self._producer.produce("strategies.proposed", strategy.to_dict(), key=strategy.strategy_id)

    def cache_set(self, key: str, value: Any, ttl: int = 3600) -> None:
        if self._redis:
            self._redis.setex(f"{self.agent_name}:{key}", ttl, json.dumps(value, default=str))

    def cache_get(self, key: str) -> Any | None:
        if self._redis:
            val = self._redis.get(f"{self.agent_name}:{key}")
            return json.loads(val) if val else None
        return None

    def cache_incr(self, key: str, ttl: int = 3600) -> int:
        if self._redis:
            full_key = f"{self.agent_name}:{key}"
            val = self._redis.incr(full_key)
            self._redis.expire(full_key, ttl)
            return val
        return 0

    def run(self) -> None:
        """Main agent loop."""
        self._running = True
        logger.info("[%s] Agent started, consuming from %s", self.agent_name, self.get_subscribed_topics())
        while self._running:
            if self._consumer:
                event = self._consumer.consume_one(timeout=1.0)
                if event:
                    self.process_event(event)

    def stop(self) -> None:
        self._running = False
        if self._consumer:
            self._consumer.stop()
        if self._producer:
            self._producer.flush()

    @property
    def stats(self) -> dict[str, Any]:
        return {"agent": self.agent_name, "events_processed": self._event_count, "alerts_generated": self._alert_count}
